mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.folders.FlattenerPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - tgplugins.datedposts.DatedPostsPlugin
context:
    data:
        site_title: TechGeneral
        author:
            name: Neil Blakey-Milner
            url: "http://www.techgeneral.org"
        google_analytics_id: UA-1410155-4
        home_url: /
meta:
    nodemeta: meta.yaml
    created: !!timestamp 2012-01-01 00:00:00
    author: Neil Blakey-Milner
markdown:
    extensions:
        - codehilite(css_class=highlight,noclasses=True,pygments_style=perldoc)

# This allows me to create directories to sort my content, while maintaining a
# flat URL structure
flattener:
    items:
        - source: posts
          target: ""
        - source: structure
          target: ""

# This removes ".html" from the end of URLs, and removes "index.html" from the end of directories.
urlcleaner:
    index_file_names:
        # Identifies the files that represents a directory listing.
        # These file names are automatically stripped away when
        # the content_url function is called.
        - index.html
    strip_extensions:
        # The following extensions are automatically removed when
        # generating the urls using content_url function.
        - html
    # This option will append a slash to the end of directory paths
    append_slash: true

sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
